import type { Form } from './types';

const form = (id: string, title: string, titleEs: string, category: string, categoryEs: string, revised: string, _size = '3 KB', format: 'PDF' | 'XLSX' = 'PDF'): Form => ({ id, title: { en: title, es: titleEs }, category: { en: category, es: categoryEs }, format, size: '3 KB', revised, description: formDescriptions[id] ?? { en: `Use this form for ${title.toLowerCase()}.`, es: `Use este formulario para ${titleEs.toLowerCase()}.` } });

const formDescriptions: Record<string, Form['description']> = {
  'F-101': { en: 'Open a new residential or business water account; include identification and proof of occupancy.', es: 'Abra una cuenta nueva de agua residencial o comercial; incluya identificación y comprobante de ocupación.' },
  'F-102': { en: 'Schedule a final meter read, close an account, and provide a forwarding address.', es: 'Programe una lectura final del medidor, cierre una cuenta y proporcione una dirección de reenvío.' },
  'F-103': { en: 'Authorize another person to discuss a water account with the District.', es: 'Autorice a otra persona para hablar sobre una cuenta de agua con el Distrito.' },
  'F-104': { en: 'Enroll an account in recurring bank-account payments.', es: 'Inscriba una cuenta en pagos recurrentes por cuenta bancaria.' },
  'F-105': { en: 'Update the mailing address used for bills and account notices.', es: 'Actualice la dirección postal utilizada para facturas y avisos de cuenta.' },
  'F-204': { en: 'Request a payment arrangement before an account becomes past due.', es: 'Solicite un acuerdo de pago antes de que una cuenta quede vencida.' },
  'F-205': { en: 'Request review of charges caused by a qualifying repaired concealed leak.', es: 'Solicite revisión de cargos causados por una fuga oculta reparada que califique.' },
  'F-206': { en: 'Apply for the fictional customer assistance program using income and household information.', es: 'Solicite el programa ficticio de asistencia al cliente usando información de ingresos y hogar.' },
  'F-207': { en: 'Ask the District to review a returned or reversed payment.', es: 'Solicite al Distrito revisar un pago devuelto o revertido.' },
  'F-306': { en: 'Request reimbursement after an eligible conservation purchase or completed project.', es: 'Solicite reembolso después de una compra de conservación elegible o un proyecto completado.' },
  'F-307': { en: 'Request approval before beginning an eligible landscape conversion.', es: 'Solicite aprobación antes de comenzar una conversión de jardín elegible.' },
  'F-308': { en: 'Request a short-term variance from current outdoor water-use rules.', es: 'Solicite una variación a corto plazo de las reglas actuales de uso exterior de agua.' },
  'F-309': { en: 'Notify Conservation before filling a pool when a notice or program requires it.', es: 'Notifique a Conservación antes de llenar una piscina cuando lo requiera un aviso o programa.' },
  'F-401': { en: 'Start Engineering review for a proposed development or new water connection.', es: 'Inicie la revisión de Ingeniería para un desarrollo propuesto o una nueva conexión de agua.' },
  'F-402': { en: 'Confirm that a development plan package includes each required review item.', es: 'Confirme que un paquete de planos de desarrollo incluya cada elemento de revisión requerido.' },
  'F-403': { en: 'Request approval for work that may affect a District water main or facility.', es: 'Solicite aprobación para trabajo que pueda afectar una tubería principal o instalación del Distrito.' },
  'F-404': { en: 'Apply to rent a District hydrant meter for an approved temporary use.', es: 'Solicite alquilar un medidor de hidrante del Distrito para un uso temporal aprobado.' },
  'F-405': { en: 'Request available fire-flow information for planning or design.', es: 'Solicite información disponible de flujo contra incendios para planificación o diseño.' },
  'F-409': { en: 'Submit annual test results for a required backflow prevention assembly.', es: 'Presente resultados anuales de prueba para un conjunto requerido de prevención de reflujo.' },
  'F-410': { en: 'Provide information needed for a cross-connection control survey.', es: 'Proporcione la información necesaria para una encuesta de control de conexiones cruzadas.' },
  'F-411': { en: 'Report a non-emergency drinking-water quality concern for follow-up.', es: 'Reporte una preocupación no urgente sobre la calidad del agua potable para seguimiento.' },
  'F-501': { en: 'Help identify existing public records and state how you prefer to receive a response.', es: 'Ayude a identificar registros públicos existentes e indique cómo prefiere recibir una respuesta.' },
  'F-502': { en: 'Ask the District Clerk to consider a proposed Board agenda topic.', es: 'Solicite a la Secretaría del Distrito considerar un tema propuesto para la agenda de la Junta.' },
  'F-503': { en: 'Submit a claim against the District using the required claim information.', es: 'Presente una reclamación contra el Distrito usando la información de reclamación requerida.' },
  'F-601': { en: 'Apply for a posted District position and provide the required employment information.', es: 'Solicite un puesto publicado por el Distrito y proporcione la información de empleo requerida.' },
  'F-602': { en: 'Share interest in future District volunteer opportunities.', es: 'Comparta su interés en futuras oportunidades de voluntariado del Distrito.' },
};

export const forms: Form[] = [
  form('F-101', 'Application for water service', 'Solicitud de servicio de agua', 'Customer account', 'Cuenta del cliente', '2026-01-12', '322 KB'),
  form('F-102', 'Request to stop service', 'Solicitud para suspender servicio', 'Customer account', 'Cuenta del cliente', '2025-10-04', '181 KB'),
  form('F-103', 'Authorized user designation', 'Designación de usuario autorizado', 'Customer account', 'Cuenta del cliente', '2025-08-21', '148 KB'),
  form('F-104', 'Automatic payment enrollment', 'Inscripción en pago automático', 'Customer account', 'Cuenta del cliente', '2026-02-19', '212 KB'),
  form('F-105', 'Mailing address change', 'Cambio de dirección postal', 'Customer account', 'Cuenta del cliente', '2025-06-09', '129 KB'),
  form('F-204', 'Payment arrangement request', 'Solicitud de acuerdo de pago', 'Billing and payment', 'Facturación y pagos', '2026-03-04', '201 KB'),
  form('F-205', 'Leak adjustment request', 'Solicitud de ajuste por fuga', 'Billing and payment', 'Facturación y pagos', '2026-01-30', '249 KB'),
  form('F-206', 'Low-income assistance application', 'Solicitud de asistencia de bajos ingresos', 'Billing and payment', 'Facturación y pagos', '2025-11-17', '387 KB'),
  form('F-207', 'Returned payment review', 'Revisión de pago devuelto', 'Billing and payment', 'Facturación y pagos', '2025-07-28', '164 KB'),
  form('F-306', 'Conservation rebate application', 'Solicitud de reembolso por conservación', 'Conservation', 'Conservación', '2026-04-16', '514 KB'),
  form('F-307', 'Landscape conversion pre-approval', 'Aprobación previa de conversión de jardín', 'Conservation', 'Conservación', '2026-04-16', '476 KB'),
  form('F-308', 'Water use variance request', 'Solicitud de variación de uso de agua', 'Conservation', 'Conservación', '2025-09-11', '231 KB'),
  form('F-309', 'Pool fill notification', 'Notificación de llenado de piscina', 'Conservation', 'Conservación', '2025-09-11', '133 KB'),
  form('F-401', 'Development service request', 'Solicitud de servicio para desarrollo', 'Development and permits', 'Desarrollo y permisos', '2026-02-02', '658 KB'),
  form('F-402', 'Plan review submittal checklist', 'Lista de verificación para revisión de planos', 'Development and permits', 'Desarrollo y permisos', '2026-02-02', '421 KB'),
  form('F-403', 'Water main encroachment permit', 'Permiso de invasión de tubería de agua', 'Development and permits', 'Desarrollo y permisos', '2025-12-14', '391 KB'),
  form('F-404', 'Hydrant meter rental agreement', 'Contrato de alquiler de medidor de hidrante', 'Development and permits', 'Desarrollo y permisos', '2025-10-28', '267 KB'),
  form('F-405', 'Fire flow information request', 'Solicitud de información de flujo contra incendios', 'Development and permits', 'Desarrollo y permisos', '2025-08-02', '182 KB'),
  form('F-409', 'Backflow test report', 'Informe de prueba antirretorno', 'Water quality', 'Calidad del agua', '2026-01-01', '196 KB'),
  form('F-410', 'Cross-connection survey', 'Encuesta de conexión cruzada', 'Water quality', 'Calidad del agua', '2025-10-12', '287 KB'),
  form('F-411', 'Water quality concern report', 'Informe de preocupación sobre calidad del agua', 'Water quality', 'Calidad del agua', '2025-05-18', '145 KB'),
  form('F-501', 'Public records request', 'Solicitud de registros públicos', 'District government', 'Gobierno del distrito', '2026-02-12', '203 KB'),
  form('F-502', 'Board agenda item request', 'Solicitud de punto de agenda de la Junta', 'District government', 'Gobierno del distrito', '2025-07-07', '171 KB'),
  form('F-503', 'Claim against the district', 'Reclamación contra el distrito', 'District government', 'Gobierno del distrito', '2025-03-14', '362 KB'),
  form('F-601', 'Employment application', 'Solicitud de empleo', 'Employment', 'Empleo', '2026-05-01', '508 KB'),
  form('F-602', 'Volunteer interest form', 'Formulario de interés para voluntariado', 'Employment', 'Empleo', '2025-11-20', '154 KB'),
];
