import type { Notice } from './types';

const notice = (slug: string, title: string, titleEs: string, summary: string, summaryEs: string, department: string, posted: string, urgent = false): Notice => ({ slug, title: { en: title, es: titleEs }, summary: { en: summary, es: summaryEs }, department, posted, year: Number(posted.slice(0, 4)), urgent });

export const notices: Notice[] = [
  notice('scheduled-maintenance-aug-2026', 'Scheduled maintenance: Mesa Creek pressure zone', 'Mantenimiento programado: zona de presión Mesa Creek', 'Routine valve maintenance may cause brief pressure changes on August 18, 2026, from 9 a.m. to 2 p.m.', 'El mantenimiento rutinario de válvulas puede causar cambios breves de presión el 18 de agosto de 2026, de 9 a.m. a 2 p.m.', 'Operations', '2026-07-28'),
  notice('board-public-hearing-rates', 'Public hearing notice: proposed 2027 water rates', 'Aviso de audiencia pública: tarifas de agua propuestas para 2027', 'The Board will receive public comment before considering the proposed rate schedule.', 'La Junta recibirá comentarios públicos antes de considerar el calendario de tarifas propuesto.', 'District Clerk', '2026-07-22'),
  notice('stage-1-conservation', 'Stage 1 conservation rules remain in effect', 'Las reglas de conservación de etapa 1 siguen vigentes', 'Outdoor watering remains limited to two assigned days each week. Repair leaks promptly.', 'El riego exterior sigue limitado a dos días asignados cada semana. Repare las fugas de inmediato.', 'Conservation', '2026-07-15'),
  notice('canyon-view-reservoir-progress', 'Canyon View Reservoir project update', 'Actualización del proyecto del embalse Canyon View', 'The contractor will begin grading at the north access road in early August.', 'El contratista comenzará nivelación en el camino de acceso norte a principios de agosto.', 'Engineering', '2026-07-08'),
  notice('holiday-office-closure-september', 'District offices closed September 7', 'Oficinas del distrito cerradas el 7 de septiembre', 'Customer service counters will be closed for the Labor Day holiday. Emergency response remains available.', 'Los mostradores de servicio al cliente estarán cerrados por el Día del Trabajo. La respuesta de emergencia seguirá disponible.', 'Customer Services', '2026-07-02'),
  notice('consumer-confidence-report-2025', '2025 Consumer Confidence Report is available', 'El Informe de Confianza del Consumidor 2025 está disponible', 'The annual water quality report is now available in English and Spanish.', 'El informe anual de calidad del agua ya está disponible en inglés y español.', 'Water Quality', '2026-06-25'),
  notice('hydrant-testing-east-basin', 'Hydrant testing begins in East Basin', 'Comienza la prueba de hidrantes en East Basin', 'Testing may temporarily discolor water. If this occurs, run cold water until clear.', 'Las pruebas pueden decolorar temporalmente el agua. Si ocurre, deje correr agua fría hasta que salga clara.', 'Operations', '2026-06-17'),
  notice('summer-billing-tips', 'Summer billing tips and usage alerts', 'Consejos de facturación de verano y alertas de uso', 'High outdoor use can increase bills. Learn how to read your meter and find leaks.', 'El alto uso exterior puede aumentar las facturas. Aprenda a leer su medidor y encontrar fugas.', 'Customer Services', '2026-06-10'),
  notice('district-budget-adopted', 'Board adopts fiscal year 2026-27 budget', 'La Junta adopta el presupuesto del año fiscal 2026-27', 'The adopted budget funds water reliability, system maintenance, and customer assistance.', 'El presupuesto adoptado financia confiabilidad del agua, mantenimiento del sistema y asistencia al cliente.', 'Finance', '2026-06-03'),
  notice('brindle-hills-main-replacement', 'Brindle Hills water main replacement begins', 'Comienza el reemplazo de tubería principal en Brindle Hills', 'Work will occur weekdays from 7 a.m. to 4 p.m. on Juniper Avenue through October.', 'El trabajo se realizará de lunes a viernes de 7 a.m. a 4 p.m. en Juniper Avenue hasta octubre.', 'Engineering', '2026-05-27'),
  notice('backflow-report-due', 'Annual backflow test reports due June 30', 'Informes anuales de prueba antirretorno vencen el 30 de junio', 'Customers with required backflow assemblies must submit a completed test report.', 'Clientes con conjuntos antirretorno requeridos deben presentar un informe de prueba completado.', 'Water Quality', '2026-05-19'),
  notice('memorial-day-closure', 'District offices closed May 25', 'Oficinas del distrito cerradas el 25 de mayo', 'Offices will be closed for Memorial Day. Report water emergencies to the 24-hour line.', 'Las oficinas estarán cerradas por el Día de los Caídos. Reporte emergencias de agua a la línea de 24 horas.', 'Customer Services', '2026-05-12'),
  notice('annual-flushing-program', 'Annual system flushing program starts May 11', 'El programa anual de lavado del sistema inicia el 11 de mayo', 'Crews will flush water mains to maintain water quality across the distribution system.', 'Las cuadrillas lavarán tuberías para mantener la calidad del agua en el sistema de distribución.', 'Operations', '2026-05-05'),
  notice('conservation-rebate-funding', 'Conservation rebate funding is available', 'Hay fondos disponibles para reembolsos de conservación', 'Limited funding is available for qualifying high-efficiency equipment and landscape conversions.', 'Hay fondos limitados para equipos eficientes y conversiones de jardines que califiquen.', 'Conservation', '2026-04-28'),
  notice('may-board-election', 'Notice of board election and filing period', 'Aviso de elección de junta y período de presentación', 'Two director seats will appear on the November ballot. The filing period opens July 13.', 'Dos asientos de director aparecerán en la boleta de noviembre. El período de presentación abre el 13 de julio.', 'District Clerk', '2026-04-21'),
  notice('mesa-creek-pump-station', 'Mesa Creek Pump Station rehabilitation completed', 'Rehabilitación de la estación de bombeo Mesa Creek completada', 'The upgraded station improves reliability during summer peak demand.', 'La estación mejorada aumenta la confiabilidad durante la demanda máxima de verano.', 'Engineering', '2026-04-14'),
  notice('drought-preparedness-open-house', 'Drought preparedness open house: April 23', 'Casa abierta sobre preparación para sequía: 23 de abril', 'Meet conservation staff, see rebate options, and learn about the current water supply outlook.', 'Conozca al personal de conservación, vea opciones de reembolso y aprenda sobre el suministro actual.', 'Conservation', '2026-04-06'),
  notice('water-week-student-art', 'Water Week student art showcase', 'Exhibición de arte estudiantil de la Semana del Agua', 'Visit the Arroyo Vale Library to see student artwork celebrating water stewardship.', 'Visite la Biblioteca Arroyo Vale para ver arte estudiantil sobre el cuidado del agua.', 'Community Relations', '2026-03-30'),
  notice('spring-meter-reading', 'Spring meter-reading schedule', 'Calendario de lectura de medidores de primavera', 'Meters are read throughout April. Keep access clear and secure pets on reading days.', 'Los medidores se leen durante abril. Mantenga el acceso libre y asegure las mascotas los días de lectura.', 'Customer Services', '2026-03-23'),
  notice('water-quality-monitoring', 'Winter water quality monitoring summary', 'Resumen de monitoreo de calidad del agua de invierno', 'All routine monitoring results met applicable drinking water standards.', 'Todos los resultados de monitoreo rutinario cumplieron los estándares aplicables de agua potable.', 'Water Quality', '2026-02-26'),
];
