import type { Project } from './types';

export const projects: Project[] = [
  { name: { en: 'Canyon View Reservoir seismic upgrade', es: 'Mejora sísmica del embalse Canyon View' }, status: { en: 'Construction', es: 'Construcción' }, budget: '$12.8 million', timeline: { en: '2025 to 2027', es: '2025 a 2027' }, description: { en: 'Improves emergency storage reliability and access for inspection crews.', es: 'Mejora la confiabilidad del almacenamiento de emergencia y el acceso de inspección.' } },
  { name: { en: 'Brindle Hills water main replacement', es: 'Reemplazo de tubería principal en Brindle Hills' }, status: { en: 'Construction', es: 'Construcción' }, budget: '$4.6 million', timeline: { en: 'June to October 2026', es: 'Junio a octubre de 2026' }, description: { en: 'Replaces aging cast iron main and improves fire-flow capacity.', es: 'Reemplaza una tubería de hierro fundido antigua y mejora la capacidad de flujo contra incendios.' } },
  { name: { en: 'Mesa Creek Pump Station rehabilitation', es: 'Rehabilitación de la estación de bombeo Mesa Creek' }, status: { en: 'Complete', es: 'Completado' }, budget: '$2.1 million', timeline: { en: 'Completed April 2026', es: 'Completado en abril de 2026' }, description: { en: 'Updated controls, pumps, and standby power for peak-demand resilience.', es: 'Actualizó controles, bombas y energía de reserva para mayor resiliencia.' } },
  { name: { en: 'Advanced meter infrastructure rollout', es: 'Implementación de infraestructura avanzada de medidores' }, status: { en: 'Design', es: 'Diseño' }, budget: '$8.4 million', timeline: { en: '2026 to 2028', es: '2026 a 2028' }, description: { en: 'Will provide timely leak alerts and more detailed customer use information.', es: 'Proporcionará alertas oportunas de fugas e información más detallada de uso.' } },
  { name: { en: 'North Basin intertie study', es: 'Estudio de interconexión North Basin' }, status: { en: 'Planning', es: 'Planificación' }, budget: '$640,000', timeline: { en: '2026', es: '2026' }, description: { en: 'Evaluates an emergency supply connection with a neighboring agency.', es: 'Evalúa una conexión de suministro de emergencia con una agencia vecina.' } },
  { name: { en: 'Juniper Avenue sewer protection relocation', es: 'Reubicación de protección de alcantarillado en Juniper Avenue' }, status: { en: 'Construction', es: 'Construcción' }, budget: '$1.9 million', timeline: { en: '2026', es: '2026' }, description: { en: 'Separates water facilities from a planned county drainage improvement.', es: 'Separa instalaciones de agua de una mejora de drenaje del condado planificada.' } },
  { name: { en: 'Well 4 treatment upgrade', es: 'Mejora de tratamiento del Pozo 4' }, status: { en: 'Design', es: 'Diseño' }, budget: '$3.7 million', timeline: { en: '2026 to 2027', es: '2026 a 2027' }, description: { en: 'Adds treatment capacity and improves operational flexibility.', es: 'Agrega capacidad de tratamiento y mejora la flexibilidad operativa.' } },
  { name: { en: 'Basin Way customer counter renewal', es: 'Renovación del mostrador de clientes de Basin Way' }, status: { en: 'Complete', es: 'Completado' }, budget: '$325,000', timeline: { en: 'Completed January 2026', es: 'Completado en enero de 2026' }, description: { en: 'Improved accessible counter access, acoustics, and multilingual wayfinding.', es: 'Mejoró el acceso a mostradores, la acústica y señalización multilingüe.' } },
];
