import type { Bilingual } from './types';

const b = (en: string, es: string): Bilingual => ({ en, es });

export type ServiceSubmission = {
  heading: Bilingual;
  introduction: Bilingual;
  steps: Bilingual[];
  note?: Bilingual;
  forms?: string[];
};

// Clear delivery instructions make static service pages useful without implying
// that a visitor has completed a transaction online.
export const serviceSubmissions: Record<string, ServiceSubmission> = {
  'start-water-service': {
    heading: b('Submit your service request', 'Presente su solicitud de servicio'),
    introduction: b('Download Form F-101, complete every required field, and include the documents listed above. A request is not scheduled until Customer Services can verify the account holder.', 'Descargue el Formulario F-101, complete todos los campos requeridos e incluya los documentos indicados arriba. Una solicitud no se programa hasta que Servicios al Cliente pueda verificar al titular de la cuenta.'),
    steps: [b('Return the signed form and copies of your identification and proof of occupancy to Customer Services by email, mail, or at the customer counter.', 'Entregue el formulario firmado y copias de su identificación y comprobante de ocupación a Servicios al Cliente por correo electrónico, correo postal o en el mostrador.'), b('State the requested start date and a daytime phone number in case staff need to reach you.', 'Indique la fecha de inicio solicitada y un número de teléfono de día en caso de que el personal necesite comunicarse con usted.'), b('Wait for confirmation before assuming water service has been activated; a deposit may be due before activation.', 'Espere la confirmación antes de asumir que el servicio de agua ha sido activado; puede requerirse un depósito antes de la activación.')],
  },
  'stop-water-service': {
    heading: b('Schedule your final meter read', 'Programe su lectura final del medidor'),
    introduction: b('Use Form F-102 to request closure. Submit the form before the requested date so staff can schedule a final read and prepare your final statement.', 'Use el Formulario F-102 para solicitar el cierre. Presente el formulario antes de la fecha solicitada para que el personal pueda programar una lectura final y preparar su estado de cuenta final.'),
    steps: [b('Return the completed request by email, mail, or at the customer counter; include your account number or the service address.', 'Entregue la solicitud completa por correo electrónico, correo postal o en el mostrador; incluya su número de cuenta o la dirección del servicio.'), b('Give a forwarding address and a phone number where staff can reach you if access to the meter is blocked.', 'Proporcione una dirección de reenvío y un número de teléfono donde el personal pueda localizarle si el acceso al medidor está bloqueado.'), b('Keep water use to a minimum after the final-read date until the account is confirmed closed.', 'Mantenga el uso de agua al mínimo después de la fecha de lectura final hasta que se confirme el cierre de la cuenta.')],
  },
  'pay-your-bill': {
    heading: b('Choose the payment method that fits your timing', 'Elija el método de pago que se ajuste a su tiempo'),
    introduction: b('Use the payment options below to compare posting times. Have the account number and service address from your bill available before making a payment or requesting assistance.', 'Use las opciones de pago a continuación para comparar los tiempos de registro. Tenga disponible el número de cuenta y la dirección del servicio de su factura antes de realizar un pago o solicitar asistencia.'),
    steps: [b('For automatic payment, complete Form F-104 before the next billing cycle and keep a copy of your enrollment request.', 'Para el pago automático, complete el Formulario F-104 antes del próximo ciclo de facturación y conserve una copia de su solicitud de inscripción.'), b('If you need a payment arrangement or assistance, submit the applicable form or call Customer Services before the due date.', 'Si necesita un acuerdo de pago o asistencia, presente el formulario correspondiente o llame a Servicios al Cliente antes de la fecha de vencimiento.'), b('Retain your receipt, confirmation number, or proof of mailing until the payment is reflected on your account.', 'Conserve su recibo, número de confirmación o comprobante de envío hasta que el pago se refleje en su cuenta.')],
  },
  'leak-adjustment': {
    heading: b('Send a complete adjustment request', 'Envíe una solicitud de ajuste completa'),
    introduction: b('After the leak is repaired, complete Form F-205 and attach the repair documentation. Incomplete requests can delay review because staff must verify the account, usage, and repair date.', 'Después de reparar la fuga, complete el Formulario F-205 y adjunte la documentación de reparación. Las solicitudes incompletas pueden retrasar la revisión porque el personal debe verificar la cuenta, el uso y la fecha de reparación.'),
    steps: [b('Include the paid repair invoice or receipts, a description of the leak, and any available before-and-after meter readings or photos.', 'Incluya la factura de reparación pagada o recibos, una descripción de la fuga y cualquier lectura del medidor o foto disponible de antes y después.'), b('Return the signed form and attachments to Customer Services by email, mail, or at the customer counter within 60 days of the repair invoice.', 'Entregue el formulario firmado y los archivos adjuntos a Servicios al Cliente por correo electrónico, correo postal o en el mostrador dentro de 60 días de la factura de reparación.'), b('Keep originals until you receive a written decision; staff may ask for clarification or an additional document.', 'Conserve los originales hasta recibir una decisión por escrito; el personal puede solicitar aclaración o un documento adicional.')],
  },
  'report-water-problem': {
    heading: b('Report an urgent water-system concern', 'Reporte un problema urgente del sistema de agua'),
    introduction: b('For a main break, flooding, no water, or a potentially unsafe condition, call the 24-hour Operations line at (555) 010-0111. Do not rely on email or a form for an urgent response.', 'Para una rotura de tubería principal, inundación, falta de agua o una condición potencialmente peligrosa, llame a la línea de Operaciones de 24 horas al (555) 010-0111. No dependa del correo electrónico ni de un formulario para obtener una respuesta urgente.'),
    steps: [b('Move away from rushing water, damaged pavement, traffic, or electrical hazards. Call 911 first when there is an immediate threat to life or safety.', 'Aléjese del agua que corre, pavimento dañado, tráfico o peligros eléctricos. Llame primero al 911 cuando exista una amenaza inmediata para la vida o la seguridad.'), b('Tell the dispatcher the nearest address or cross street, what you see, when it began, and a safe number for a callback.', 'Indique al despachador la dirección o intersección más cercana, lo que observa, cuándo comenzó y un número seguro para devolver la llamada.'), b('Do not operate valves, enter flooded areas, or open hydrants. District crews will assess the location and provide an update when possible.', 'No opere válvulas, entre a zonas inundadas ni abra hidrantes. Las cuadrillas del Distrito evaluarán el lugar y proporcionarán una actualización cuando sea posible.')],
    note: b('For a water-quality concern that is not urgent, contact Water Quality during business hours at (555) 010-0133.', 'Para una preocupación de calidad del agua que no sea urgente, comuníquese con Calidad del Agua durante el horario de oficina al (555) 010-0133.'),
  },
  'water-quality-records': {
    heading: b('Request the right report or result', 'Solicite el informe o resultado correcto'),
    introduction: b('Start with the annual Consumer Confidence Report or the recent monitoring information posted by the District. For a specific result, identify the year, location, and contaminant or test you need.', 'Comience con el Informe de Confianza del Consumidor anual o la información reciente de monitoreo publicada por el Distrito. Para un resultado específico, identifique el año, la ubicación y el contaminante o prueba que necesita.'),
    steps: [b('Download the available report or contact Water Quality to request a paper copy or alternate format.', 'Descargue el informe disponible o comuníquese con Calidad del Agua para solicitar una copia en papel o un formato alternativo.'), b('For laboratory or monitoring records, provide as much detail as possible so staff can locate the correct sampling period.', 'Para registros de laboratorio o monitoreo, proporcione la mayor cantidad de detalles posible para que el personal pueda localizar el periodo de muestreo correcto.'), b('Use the public-records request service when you need existing records that are not posted online.', 'Use el servicio de solicitud de registros públicos cuando necesite registros existentes que no estén publicados en línea.')],
  },
  'conservation-rebate': {
    heading: b('Apply before funds are committed', 'Solicite antes de que se comprometan los fondos'),
    forms: ['F-307'],
    introduction: b('Funding is limited and some projects require approval before work begins. Review the program requirements, then use the form that matches your project.', 'Los fondos son limitados y algunos proyectos requieren aprobación antes de comenzar el trabajo. Revise los requisitos del programa y luego use el formulario que corresponda a su proyecto.'),
    steps: [b('For a landscape conversion, request pre-approval with Form F-307 before removing turf or buying materials.', 'Para una conversión de jardín, solicite aprobación previa con el Formulario F-307 antes de retirar césped o comprar materiales.'), b('After an eligible purchase or approved project is complete, submit Form F-306 with itemized receipts, proof of payment, and the requested photos.', 'Después de completar una compra elegible o un proyecto aprobado, presente el Formulario F-306 con recibos detallados, comprobante de pago y las fotos solicitadas.'), b('Return the complete packet to Conservation by email, mail, or in person and keep copies until the rebate decision is issued.', 'Entregue el paquete completo a Conservación por correo electrónico, correo postal o en persona y conserve copias hasta que se emita la decisión del reembolso.')],
  },
  'outdoor-water-use': {
    heading: b('Follow the current stage and your assigned days', 'Siga la etapa actual y sus días asignados'),
    forms: ['F-308'],
    introduction: b('The conservation alert at the top of the site states the current stage. Check it before changing irrigation schedules because restrictions can change as water-supply conditions change.', 'La alerta de conservación en la parte superior del sitio indica la etapa actual. Consúltela antes de cambiar los horarios de riego porque las restricciones pueden cambiar según las condiciones de suministro de agua.'),
    steps: [b('Confirm your assigned outdoor-watering days with Conservation if you are new to the District or are unsure which schedule applies to your address.', 'Confirme sus días asignados de riego exterior con Conservación si es nuevo en el Distrito o no está seguro de qué horario corresponde a su dirección.'), b('Set irrigation to avoid runoff, overspray, and watering during prohibited hours; repair leaks as soon as they are discovered.', 'Configure el riego para evitar escurrimiento, rociado excesivo y riego durante horas prohibidas; repare las fugas en cuanto se descubran.'), b('If a short-term variance is needed for an eligible reason, request it before watering outside the rules.', 'Si necesita una variación a corto plazo por una razón elegible, solicítela antes de regar fuera de las reglas.')],
  },
  'new-development': {
    heading: b('Begin with a complete engineering submittal', 'Comience con una presentación completa a Ingeniería'),
    introduction: b('New connections require capacity review and may require conditions, fees, easements, or off-site improvements. Schedule a pre-application conversation before investing in final plans.', 'Las nuevas conexiones requieren revisión de capacidad y pueden requerir condiciones, tarifas, servidumbres o mejoras fuera del sitio. Programe una conversación previa a la solicitud antes de invertir en planos finales.'),
    steps: [b('Request a pre-application meeting with Engineering and bring the project address, parcel information, proposed use, and expected demand.', 'Solicite una reunión previa a la solicitud con Ingeniería y lleve la dirección del proyecto, información de la parcela, uso propuesto y demanda esperada.'), b('Submit Form F-401, the F-402 checklist, utility plans, and every supporting item listed by Engineering.', 'Presente el Formulario F-401, la lista de verificación F-402, los planos de servicios y cada documento de respaldo indicado por Ingeniería.'), b('Do not begin construction or assume water capacity is reserved until the District issues written conditions and required approvals.', 'No comience la construcción ni suponga que la capacidad de agua está reservada hasta que el Distrito emita condiciones y aprobaciones por escrito.')],
  },
  'backflow-test': {
    heading: b('File the signed annual test report', 'Presente el informe anual de prueba firmado'),
    introduction: b('Use a qualified tester and submit Form F-409 after any required repairs are complete. The report must identify the service address, assembly, test date, and tester certification.', 'Use un inspector calificado y presente el Formulario F-409 después de completar cualquier reparación requerida. El informe debe identificar la dirección del servicio, el conjunto, la fecha de prueba y la certificación del inspector.'),
    steps: [b('Have the tester complete and sign every required field; keep a copy for the property record.', 'Pida al inspector que complete y firme cada campo requerido; conserve una copia para el registro de la propiedad.'), b('Send the report to Water Quality by email, mail, or at the District counter before the annual due date shown in the notice.', 'Envíe el informe a Calidad del Agua por correo electrónico, correo postal o en el mostrador del Distrito antes de la fecha anual de vencimiento indicada en el aviso.'), b('Correct failed tests promptly and submit the retest documentation. Contact Water Quality if an extension is needed before the deadline.', 'Corrija las pruebas fallidas con prontitud y presente la documentación de la nueva prueba. Comuníquese con Calidad del Agua si necesita una extensión antes de la fecha límite.')],
  },
  'public-records-request': {
    heading: b('Submit a focused public-records request', 'Presente una solicitud de registros públicos enfocada'),
    introduction: b('Form F-501 is optional but helps the District identify existing records and respond efficiently. You do not need to explain why you want the records.', 'El Formulario F-501 es opcional, pero ayuda al Distrito a identificar registros existentes y responder eficientemente. No necesita explicar por qué desea los registros.'),
    steps: [b('Describe the records by subject, date range, project, address, or another useful detail. Ask for inspection, electronic copies, or paper copies.', 'Describa los registros por tema, rango de fechas, proyecto, dirección u otro detalle útil. Solicite inspección, copias electrónicas o copias en papel.'), b('Email, mail, or deliver the request to the District Clerk. Include a preferred response method so staff can contact you about clarification or estimated costs.', 'Envíe por correo electrónico, correo postal o entregue la solicitud a la Secretaría del Distrito. Incluya un método preferido de respuesta para que el personal pueda contactarle sobre aclaraciones o costos estimados.'), b('Submit one focused request at a time when possible. The Clerk may ask you to narrow a broad request so responsive records can be located.', 'Presente una solicitud enfocada a la vez cuando sea posible. La Secretaría puede pedirle que reduzca una solicitud amplia para poder localizar los registros correspondientes.')],
  },
  'board-meeting-comment': {
    heading: b('Make your comment part of the public process', 'Haga que su comentario forme parte del proceso público'),
    introduction: b('Review the agenda before the meeting to understand when public comment will be taken. Written comments should identify the meeting date and agenda item, if applicable.', 'Revise la agenda antes de la reunión para entender cuándo se recibirán comentarios públicos. Los comentarios por escrito deben identificar la fecha de la reunión y el punto de agenda, si corresponde.'),
    steps: [b('To speak in person, arrive before the meeting begins and follow the Clerk’s sign-in or speaker-card instructions.', 'Para hablar en persona, llegue antes de que comience la reunión y siga las instrucciones de registro o tarjeta de orador de la Secretaría.'), b('Send written comments to the District Clerk by 3 p.m. on the meeting date for distribution when feasible.', 'Envíe comentarios por escrito a la Secretaría del Distrito antes de las 3 p.m. del día de la reunión para su distribución cuando sea posible.'), b('Keep remarks within the posted time limit and avoid sharing personal account or other sensitive information during public comment.', 'Mantenga sus comentarios dentro del límite de tiempo publicado y evite compartir información personal de cuenta u otra información confidencial durante el comentario público.')],
  },
  'job-opportunities': {
    heading: b('Apply for a posted opening', 'Solicite una vacante publicada'),
    introduction: b('A complete application must be received by the deadline in the job bulletin. The District evaluates applications against the listed minimum qualifications, not against information provided after the closing time.', 'Una solicitud completa debe recibirse antes de la fecha límite indicada en el anuncio de empleo. El Distrito evalúa las solicitudes según las calificaciones mínimas indicadas, no según información proporcionada después de la hora de cierre.'),
    steps: [b('Download Form F-601 and the job bulletin, then prepare the resume, licenses, certificates, or transcripts requested for that position.', 'Descargue el Formulario F-601 y el anuncio de empleo, luego prepare el currículum, licencias, certificados o expedientes académicos solicitados para ese puesto.'), b('Submit every requested document to Human Resources using the delivery method and deadline listed in the bulletin.', 'Presente cada documento solicitado a Recursos Humanos utilizando el método de entrega y la fecha límite indicados en el anuncio.'), b('Keep a copy of the complete packet and monitor the email address you provided for selection-process updates.', 'Conserve una copia del paquete completo y revise la dirección de correo electrónico que proporcionó para recibir actualizaciones del proceso de selección.')],
  },
  'district-map': {
    heading: b('Use the map as a preliminary guide', 'Use el mapa como guía preliminar'),
    introduction: b('Enter a complete address in the service-area guide below. The result is for planning only and does not confirm that a connection is available or approved.', 'Ingrese una dirección completa en la guía del área de servicio a continuación. El resultado es solo para planificación y no confirma que una conexión esté disponible o aprobada.'),
    steps: [b('Review the map result and note whether the address is near a boundary or shown as an unconfirmed area.', 'Revise el resultado del mapa y observe si la dirección está cerca de un límite o se muestra como un área sin confirmar.'), b('For a purchase, construction, or development decision, contact Engineering with the parcel number and proposed use for an official review.', 'Para una decisión de compra, construcción o desarrollo, comuníquese con Ingeniería con el número de parcela y uso propuesto para una revisión oficial.'), b('Do not rely on the map alone for capacity, connection-fee, easement, or main-extension decisions.', 'No se base solo en el mapa para decisiones de capacidad, tarifas de conexión, servidumbres o extensión de tubería principal.')],
  },
};
