import { notFound } from 'next/navigation';
import Link from 'next/link';
import { notices } from '@/content/notices';
import { noticeGuidance } from '@/content/notice-guidance';
import { Breadcrumbs, ContactCard, PageStamp, SectionNav } from '@/components/interior';
import { Helpful } from '@/components/helpful';
import { Localized } from '@/components/localized';

// Kept separate so the route wrapper can resolve Next.js 15 async parameters.
export function generateStaticParams() { return notices.map((notice) => ({ slug: notice.slug })); }
export default function NoticePage({ params }: { params: { slug: string } }) { const notice = notices.find((entry) => entry.slug === params.slug); if (!notice) notFound(); const guidance = noticeGuidance(notice.department); return <main id="main-content"><Breadcrumbs items={[{ label: 'Home', href: '/' }, { label: 'Public notices', href: '/notices' }, { label: notice.title.en }]} /><div className="shell grid gap-7 py-7 lg:grid-cols-[230px_minmax(0,1fr)_260px]"><SectionNav title="Meetings & notices" links={[{ label: 'Board meetings', href: '/meetings' }, { label: 'Public notices', href: '/notices', current: true }, { label: 'Transparency & compliance', href: '/transparency/compliance' }, { label: 'Public records', href: '/services/public-records-request' }]} /><article className="prose"><p className="eyebrow m-0">{notice.department}</p><h1 className="mb-2 mt-1 text-4xl text-[#123b5d]"><Localized en={notice.title.en} es={notice.title.es} /></h1><p className="text-sm">Posted <time dateTime={notice.posted}>{notice.posted}</time></p><hr className="rule" /><p className="text-xl"><Localized en={notice.summary.en} es={notice.summary.es} /></p><section><h2><Localized en={guidance.heading.en} es={guidance.heading.es} /></h2><p><Localized en={guidance.detail.en} es={guidance.detail.es} /></p><h2><Localized en="What you can do" es="Lo que puede hacer" /></h2><ul>{guidance.actions.map((action) => <li key={action.en}><Localized en={action.en} es={action.es} /></li>)}</ul></section><p><Localized en="Please contact the responsible District division if you need a document in an accessible alternate format, have questions about the work described, or need language assistance." es="Comuníquese con la división responsable del Distrito si necesita un documento en un formato alternativo accesible, tiene preguntas sobre el trabajo descrito o necesita asistencia lingüística." /></p><h2><Localized en="Related information" es="Información relacionada" /></h2><ul><li><Link href="/notices"><Localized en="All public notices" es="Todos los avisos públicos" /></Link></li><li><Link href="/meetings"><Localized en="Board meetings and agendas" es="Reuniones y agendas de la Junta" /></Link></li><li><Link href="/contact"><Localized en="Department directory" es="Directorio de departamentos" /></Link></li></ul><PageStamp date={notice.posted} /><Helpful /></article><ContactCard division={notice.department} phone="(555) 010-0100" email="info@kestrelbasin.example" /></div></main>; }
