import Link from 'next/link';
import { ArrowRight, CalendarDays, ChevronRight, CircleDollarSign, Droplets, FileText, TriangleAlert } from 'lucide-react';
import { notices } from '@/content/notices';
import { meetings } from '@/content/meetings';
import { Localized } from '@/components/localized';
import { ParallaxHeroImage } from '@/components/parallax-hero-image';

const quickLinks = [
  { icon: CircleDollarSign, en: 'Pay your bill', es: 'Pagar su factura', body: 'Payment options, due dates, and assistance.', href: '/services/pay-your-bill' },
  { icon: Droplets, en: 'Start or stop service', es: 'Iniciar o suspender servicio', body: 'Move in, move out, or update an account.', href: '/services/start-water-service' },
  { icon: TriangleAlert, en: 'Report a water problem', es: 'Reportar un problema de agua', body: 'Leaks, pressure changes, main breaks, and discolored water.', href: '/services/report-water-problem' },
  { icon: FileText, en: 'Find a form', es: 'Encontrar formulario', body: 'Applications, permits, rebates, and public records requests.', href: '/forms' },
];

export default function HomePage() {
  const upcoming = meetings.filter((meeting) => meeting.status === 'upcoming').slice(0, 2);
  return <main id="main-content">
    <section className="relative isolate min-h-[480px] overflow-hidden border-b border-slate-500 bg-[#123b5d]">
      <ParallaxHeroImage />
      <div aria-hidden="true" className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,35,55,.92)_0%,rgba(12,48,77,.76)_38%,rgba(12,48,77,.22)_68%,rgba(12,48,77,.08)_100%)]" />
      <div className="shell relative grid gap-8 py-10 lg:grid-cols-[1.15fr_.55fr] lg:py-14"><div className="prose text-white"><p className="m-0 text-sm font-bold uppercase tracking-[.12em] text-[#f2c458]">Reliable water. Responsible stewardship.</p><h1 className="mb-4 mt-3 text-4xl font-bold leading-tight text-white md:text-5xl"><Localized en="Water service that works for every household and business." es="Servicio de agua que funciona para cada hogar y negocio." /></h1><p className="text-xl text-white"><Localized en="Kestrel Basin Water District provides safe, reliable drinking water and responsive public service to the Arroyo Vale community." es="El Distrito de Agua de Kestrel Basin brinda agua potable segura, confiable y servicio público atento a la comunidad de Arroyo Vale." /></p><div className="mt-6 flex flex-wrap gap-3"><Link href="/services" className="button border-white bg-white text-[#123b5d] hover:bg-[#e7eff3] hover:text-[#0b2d47]"><Localized en="Find a service" es="Buscar un servicio" /> <ArrowRight size={18} aria-hidden="true" /></Link><Link href="/meetings" className="button border-white bg-transparent text-white hover:bg-white hover:text-[#123b5d]"><Localized en="Board agendas & meetings" es="Agendas y reuniones de la Junta" /></Link></div></div><aside aria-label="At a glance" className="self-center border-t-8 border-[#c98b16] bg-white p-5 text-[#1d2935]"><h2 className="m-0 text-xl text-[#123b5d]"><Localized en="At a glance" es="De un vistazo" /></h2><dl className="mb-0 mt-4 divide-y divide-slate-300"><div className="py-3"><dt className="font-bold"><Localized en="Current conservation stage" es="Etapa actual de conservación" /></dt><dd className="m-0"><strong className="text-[#745400]"><Localized en="Stage 1" es="Etapa 1" /></strong> <span className="text-sm"><Localized en="Two watering days per week" es="Dos días de riego por semana" /></span></dd></div><div className="py-3"><dt className="font-bold"><Localized en="Water emergency line" es="Línea de emergencia de agua" /></dt><dd className="m-0"><a href="tel:+15550100111">(555) 010-0111</a>, <Localized en="available 24 hours" es="disponible 24 horas" /></dd></div><div className="py-3"><dt className="font-bold"><Localized en="Next Board meeting" es="Próxima reunión de la Junta" /></dt><dd className="m-0">August 12, 2026, 6:00 p.m.</dd></div></dl></aside></div>
    </section>
    <section className="shell py-7"><h2 className="text-3xl text-[#123b5d]"><Localized en="Most requested services" es="Servicios más solicitados" /></h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{quickLinks.map(({ icon: Icon, en, es, body, href }) => <article key={href} className="card p-4"><Icon className="text-[#123b5d]" aria-hidden="true" /><h3 className="mb-1 mt-3 text-xl"><Link href={href}><Localized en={en} es={es} /></Link></h3><p className="m-0 text-sm">{body}</p></article>)}</div></section>
    <section className="border-y border-slate-300 bg-[#f1f5f7]"><div className="shell grid gap-8 py-7 lg:grid-cols-2"><section aria-labelledby="meetings-heading"><div className="flex items-center justify-between border-b-2 border-[#123b5d] pb-2"><h2 id="meetings-heading" className="m-0 text-2xl text-[#123b5d]"><Localized en="Upcoming meetings" es="Próximas reuniones" /></h2><Link className="text-sm font-bold" href="/meetings"><Localized en="View all meetings" es="Ver todas las reuniones" /></Link></div><ul className="m-0 list-none divide-y divide-slate-300 p-0">{upcoming.map((meeting) => <li key={meeting.id} className="flex gap-3 py-4"><CalendarDays className="mt-1 shrink-0 text-[#123b5d]" aria-hidden="true" /><div><h3 className="m-0 text-lg"><Link href="/meetings"><Localized en={meeting.type.en} es={meeting.type.es} /></Link></h3><p className="m-0 text-sm">{meeting.date}, {meeting.time}<br /><Localized en={meeting.location.en} es={meeting.location.es} /></p><p className="mb-0 mt-1 text-sm"><a href={meeting.agenda}>Agenda (PDF, 3 KB)</a><span aria-hidden="true"> · </span>Posted {meeting.posted}</p></div></li>)}</ul></section><section aria-labelledby="notices-heading"><div className="flex items-center justify-between border-b-2 border-[#123b5d] pb-2"><h2 id="notices-heading" className="m-0 text-2xl text-[#123b5d]"><Localized en="Latest notices" es="Últimos avisos" /></h2><Link className="text-sm font-bold" href="/notices"><Localized en="View all notices" es="Ver todos los avisos" /></Link></div><ul className="m-0 list-none divide-y divide-slate-300 p-0">{notices.slice(0, 3).map((notice) => <li key={notice.slug} className="py-3"><p className="m-0 text-xs font-bold uppercase tracking-wide text-slate-600">{notice.posted} · {notice.department}</p><h3 className="mb-0 mt-1 text-lg"><Link href={`/notices/${notice.slug}`}><Localized en={notice.title.en} es={notice.title.es} /></Link></h3></li>)}</ul></section></div></section>
    <section className="shell grid gap-8 py-8 lg:grid-cols-[1.25fr_.75fr]"><section className="prose"><p className="eyebrow m-0">Capital program</p><h2 className="mb-2 mt-1 text-3xl text-[#123b5d]"><Localized en="Investing in dependable water for the next generation" es="Invirtiendo en agua confiable para la próxima generación" /></h2><p><Localized en="From reservoir resilience to neighborhood main replacement, our capital program keeps essential infrastructure ready for drought, emergencies, and everyday use." es="Desde resiliencia de embalses hasta reemplazo de tuberías vecinales, nuestro programa de capital mantiene infraestructura esencial lista para sequías, emergencias y uso diario." /></p><Link href="/transparency/compliance#projects" className="font-bold"><Localized en="Explore capital projects" es="Explorar proyectos de capital" /> <ChevronRight className="inline" size={18} aria-hidden="true" /></Link></section><aside className="border-l-4 border-[#c98b16] bg-[#fff8e9] p-5"><h2 className="m-0 text-xl text-[#123b5d]"><Localized en="Know your water" es="Conozca su agua" /></h2><p className="text-sm"><Localized en="Read the annual water quality report, see monitoring summaries, and learn how we protect your drinking water." es="Lea el informe anual de calidad del agua, vea resúmenes de monitoreo y aprenda cómo protegemos su agua potable." /></p><Link href="/services/water-quality-records" className="button secondary"><Localized en="Water quality resources" es="Recursos de calidad del agua" /></Link></aside></section>
  </main>;
}
