import Link from 'next/link';
import { Localized } from './localized';

const columns = [
  { title: ['Departments', 'Departamentos'], links: [['Customer Services', 'Servicios al Cliente', '/contact'], ['Operations', 'Operaciones', '/services/report-water-problem'], ['Engineering', 'Ingeniería', '/services/new-development'], ['Water Quality', 'Calidad del Agua', '/services/water-quality-records'], ['Conservation', 'Conservación', '/services/outdoor-water-use'], ['Finance', 'Finanzas', '/services/pay-your-bill'], ['District Clerk', 'Secretaría del Distrito', '/meetings'], ['Human Resources', 'Recursos Humanos', '/services/job-opportunities']] },
  { title: ['Services', 'Servicios'], links: [['Start service', 'Iniciar servicio', '/services/start-water-service'], ['Stop service', 'Suspender servicio', '/services/stop-water-service'], ['Pay a bill', 'Pagar factura', '/services/pay-your-bill'], ['Leak adjustment', 'Ajuste por fuga', '/services/leak-adjustment'], ['Rebate programs', 'Programas de reembolso', '/services/conservation-rebate'], ['Report a problem', 'Reportar un problema', '/services/report-water-problem'], ['Forms library', 'Biblioteca de formularios', '/forms'], ['Bill estimator', 'Calculadora de factura', '/estimator']] },
  { title: ['Resources', 'Recursos'], links: [['Public notices', 'Avisos públicos', '/notices'], ['Board meetings', 'Reuniones de la Junta', '/meetings'], ['Transparency', 'Transparencia', '/transparency/compliance'], ['Accessibility', 'Accesibilidad', '/accessibility'], ['Public records', 'Registros públicos', '/services/public-records-request'], ['Projects', 'Proyectos', '/transparency/compliance#projects'], ['Water quality reports', 'Informes de calidad del agua', '/services/water-quality-records'], ['Service area map', 'Mapa del área de servicio', '/services/district-map']] },
];

export function Footer() {
  return <footer className="mt-10 bg-[#123b5d] text-white">
    <div className="shell grid gap-8 py-8 sm:grid-cols-2 lg:grid-cols-4">
      {columns.map((column) => <section key={column.title[0]}><h2 className="m-0 border-b border-[#7891a3] pb-2 text-base"><Localized en={column.title[0]} es={column.title[1]} /></h2><ul className="mt-3 list-none space-y-1 p-0 text-sm">{column.links.map(([en, es, href]) => <li key={href}><Link className="text-white hover:text-white" href={href}><Localized en={en} es={es} /></Link></li>)}</ul></section>)}
      <address className="not-italic"><h2 className="m-0 border-b border-[#7891a3] pb-2 text-base"><Localized en="Connect" es="Conéctese" /></h2><p className="mt-3 text-sm">4100 Basin Way<br />Arroyo Vale, CA 95842</p><p className="text-sm"><strong><Localized en="Customer service:" es="Servicio al cliente:" /></strong><br /><a className="text-white" href="tel:+15550100140">(555) 010-0140</a><br />TTY: 711</p><p className="text-sm"><strong><Localized en="Office hours:" es="Horario de oficina:" /></strong><br /><Localized en="Monday to Friday, 8 a.m. to 5 p.m." es="De lunes a viernes, 8 a.m. a 5 p.m." /></p></address>
    </div>
    <div className="border-t border-[#56758b] bg-[#0c304d]"><div className="footer-legal shell flex flex-wrap items-center gap-x-4 gap-y-2 py-3 text-xs"><Link className="text-white" href="/accessibility">Accessibility statement</Link><Link className="text-white" href="/transparency/compliance">Non-discrimination & transparency</Link><Link className="text-white" href="/services/public-records-request">Public records</Link><Link className="text-white" href="/privacy">Privacy policy</Link><Link className="text-white" href="/site-map">Site map</Link><span className="footer-copyright ml-auto">© 2026 Kestrel Basin Water District demonstration</span><span className="footer-credit border-l border-[#56758b] pl-4">Designed by <a className="text-white" href="https://alectronicsolutions.com" target="_blank" rel="noopener noreferrer">Alectronic Solutions</a></span></div></div>
  </footer>;
}
