import Link from 'next/link';
import { meetings } from '@/content/meetings';
import { Breadcrumbs, ContactCard, PageStamp, SectionNav } from '@/components/interior';
import { Helpful } from '@/components/helpful';
import { Localized } from '@/components/localized';

export const metadata = { title: 'Board meetings' };
function MeetingGroup({ title, data }: { title: string; data: typeof meetings }) { return <section className="mt-7"><h2 className="border-b-2 border-[#123b5d] pb-2 text-2xl text-[#123b5d]">{title}</h2><div className="table-wrap"><table className="responsive-table"><caption className="sr-only">{title}</caption><thead><tr><th scope="col">Date and time</th><th scope="col">Meeting</th><th scope="col">Agenda and minutes</th></tr></thead><tbody>{data.map((meeting) => <tr key={meeting.id}><td data-label="Date and time"><strong>{meeting.date}</strong><br />{meeting.time}<br /><span className="text-sm"><Localized en={meeting.location.en} es={meeting.location.es} /></span></td><td data-label="Meeting"><Localized en={meeting.body.en} es={meeting.body.es} /><br /><span className="text-sm"><Localized en={meeting.type.en} es={meeting.type.es} /></span></td><td data-label="Agenda and minutes"><a href={meeting.agenda}>Agenda (PDF, 480 KB)</a><br /><span className="text-sm">Posted {meeting.posted}</span>{meeting.minutes && <><br /><a href={meeting.minutes}>Minutes (PDF, 224 KB)</a></>}</td></tr>)}</tbody></table></div></section>; }
export default function MeetingsPage() { const upcoming = meetings.filter((meeting) => meeting.status === 'upcoming'); const past = meetings.filter((meeting) => meeting.status === 'past'); return <main id="main-content"><Breadcrumbs items={[{ label: 'Home', href: '/' }, { label: 'Board meetings' }]} /><div className="shell grid gap-7 py-7 lg:grid-cols-[230px_minmax(0,1fr)_260px]"><SectionNav title="Meetings & notices" links={[{ label: 'Board meetings', href: '/meetings', current: true }, { label: 'Public notices', href: '/notices' }, { label: 'Transparency & compliance', href: '/transparency/compliance' }, { label: 'Public records', href: '/services/public-records-request' }]} /><div className="prose max-w-none"><p className="eyebrow m-0">Public participation</p><h1 className="mb-2 mt-1 text-4xl text-[#123b5d]">Board meetings</h1><p className="mt-0">The Board of Directors generally meets on the second and fourth Wednesday of each month at 6:00 p.m. Agendas are posted at least 72 hours before regular meetings, as required by the Brown Act.</p><div className="border-l-4 border-[#c98b16] bg-[#fff8e9] p-4 text-sm"><strong>How to comment</strong><p className="mb-0 mt-1">Members of the public may provide comment in person at the meeting. Written comments may be sent to the District Clerk by 3:00 p.m. on the meeting date for distribution to the Board.</p></div><MeetingGroup title="Upcoming meetings" data={upcoming} /><MeetingGroup title="Past meetings" data={past} /><PageStamp /><Helpful /></div><div className="space-y-4"><ContactCard division="District Clerk" phone="(555) 010-0100" email="clerk@kestrelbasin.example" /><aside className="border border-slate-400 p-4 text-sm"><h2 className="mt-0 text-lg text-[#123b5d]">Meeting access</h2><p>Accessible seating and language assistance are available on request. Contact the Clerk at least 72 hours before a meeting when possible.</p><p className="mb-0"><Link href="/accessibility">Accessibility statement</Link></p></aside></div></div></main>; }
